/* generated by fivmc */
/* DO NOT EDIT!! */
#define FIVMC_SYS_NAME "POSIX-linux-gnu-x86_64-32"
#define FIVMC_CMD "/home/abhijit/development/fivm/bin/fivmc --more-opt --rt-verbosity-limit 10 --rt-assertions yes --rt-library RTSJ --gc CMR --g-scoped-memory --g-scope-checks no --g-def-immortal-mem 10M --g-def-log true --rtdroid-manifest rtdroid-app-demo.xml -o rtdroid-app-demo.exe ./builds/jar/rtdroid.jar"
#define FIVMC_DIR "/home/abhijit/development/rtdroid"
#define FIVMC_HOSTINFO "Linux abhijit-Lenovo-Ideapad-Flex-15 3.13.0-49-generic #83-Ubuntu SMP Fri Apr 10 20:11:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"
#define FIVMC_DATE "2015-04-18 20:05:27 -0400"
#define FIVMC_HOMEDIR "/home/abhijit/development/fivm"
#define FIVMC_OUTPUT rtdroid_002dapp_002ddemo_002eexe
