/* generated by fivmc */
/* DO NOT EDIT!! */
#include <fivmr.h>
fivmr_Configuration rtdroid_002dapp_002ddemo_002eexe_config = {
   104857600,
   209715200,
   10485760,
   1024,
   65536,
   5,
   false
};
