/* C file for payload */
/* generated by CFileGenerator.java in fivmc */
/* based on a LinkableSet with 143 linkables */
/* DO NOT EDIT DIRECTLY. */
#include <fivmr.h>
extern fivmr_Payload rtdroid_002dapp_002ddemo_002eexe_payload;
extern uintptr_t rtdroid_002dapp_002ddemo_002eexe_stringIndex[];
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_AndroidWrapper_MAsZtvIjmUDHpVxcwSOGQ5;
fivmr_StaticTypeContext rtdroid_002dapp_002ddemo_002eexe_contexts[2];
extern fivmr_Configuration rtdroid_002dapp_002ddemo_002eexe_config;
int64_t rtdroid_002dapp_002ddemo_002eexe_staticPrimFields[25];
fivmr_Object rtdroid_002dapp_002ddemo_002eexe_staticRefFields[120];
bool rtdroid_002dapp_002ddemo_002eexe_postThreadInitCback(fivmr_ThreadState *ts);
extern uintptr_t rtdroid_002dapp_002ddemo_002eexe_typeList[];
extern fivmr_TypeStub rtdroid_002dapp_002ddemo_002eexe_stubList[];
extern uintptr_t rtdroid_002dapp_002ddemo_002eexe_degugTable[];
extern uintptr_t rtdroid_002dapp_002ddemo_002eexe_stringTable[];
extern uintptr_t rtdroid_002dapp_002ddemo_002eexe_stringDataArray[];
extern uintptr_t rtdroid_002dapp_002ddemo_002eexe_classTable[];
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_pointerArr_mPM8X1CMEIVbdR2ahlrD34;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_float_jYAb064TTl5ULSaM45eom3;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_byteArr_nhLAxLkni0PhWM81bwqQW7;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_Serializable_w2dIMIasUW2jzZi7BO5Wu7;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_long_ODGjCjLuSmdgk1yysabXl;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_StringArr_847AxcZu9gWRJWNEN8DQu5;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_Cloneable_e2xIx7PUe02GksGcFKFkr8;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_WeakReference_aIuqrQ3Ad6912mgziklPD2;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_shortArr_O9QqSxVPUYeTdeZkUTYxS2;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_String_WHsiOUfdh3VfAocbciMXp7;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_pointer_sEgXFRMZ4QGvR8UkdPirt7;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_booleanArr_gfzXZt9jGBwenAc28FEfS6;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_intArr_wA4JCC2DA3AFo22aSDOZ76;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_Class_GPw2KraYNcgDw88XQsM0a2;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_ClassArr_lBldaXgGN9Gu5f4Ma9ms16;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_vm_FCPtrArr_0jAH6IfIHGlY2R2kAFpWf7;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_double_9qhcjlYcEbW7W8Wvd29o68;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_top_bkcp4oGc4D8yEEH7nlTJj6;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_floatArr_5YlNatn3OVHrdzH9hfwKk5;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_doubleArr_mjlqzFmth2EYGUJjMUzYX3;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_char_GiXZWB9j4vBLRwx6WJyV86;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_ObjectArr_v26WGLx6a25VP6bXhOLzB5;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_Object_QdKWySJdodzDYbV6VD2VJ;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_byte_p0EiuVgIFBYQneSwHkWxN2;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_boolean_sY8z6fx1V8ILNqgtWTEA35;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_longArr_IyYJgAzIvmrHWyFYSA0Nh5;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_vm_FCPtr_RXJlkedCSLtbjp4C2SYZW2;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_charArr_l3vFjwWeWLchNa4tr5HoK5;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_void_au552JrSiVdXJTpoUumvq7;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_int_gv1gSVUGP0dW3cdLM7LmE8;
extern fivmr_TypeData rtdroid_002dapp_002ddemo_002eexe_TypeData_short_31w3AaWO7w89oLerGEZ9h3;
void rtdroid_002dapp_002ddemo_002eexe_fivmRuntime_initSystemClassLoaders(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_fivmRuntime_notifyInitialized(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_returnBuffer(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getCString(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getCStringFull(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_fromCStringInHeap(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_fromCStringFullInHeap(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_fivmRuntime_boot(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwArithmeticRTE(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwArithmeticRTE_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwNullPointerRTE(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwNullPointerRTE_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwStackOverflowRTE(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwStackOverflowRTE_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwArrayBoundsRTE_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwArrayStoreRTE_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwNegativeSizeRTE_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwClassCastRTE_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwClassChangeRTE_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwNoClassDefFoundError_inJava(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_throwNoClassDefFoundError_inNative(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_throwLinkageError_inJava(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_throwIllegalAssignmentError(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwIllegalAssignmentError_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwAbstractMethodError_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwUnsatisfiedLinkErrorForLoad(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_throwExceptionInInitializerError_inJava(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_throwReflectiveException_inJava(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_throwOutOfMemoryError_inJava(uintptr_t arg0);
void rtdroid_002dapp_002ddemo_002eexe_throwIllegalMonitorStateException_inJava(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_fromUTF16Sequence(uintptr_t arg0,uintptr_t arg1,int32_t arg2);
int32_t rtdroid_002dapp_002ddemo_002eexe_stringLength(uintptr_t arg0,uintptr_t arg1);
int32_t rtdroid_002dapp_002ddemo_002eexe_cstringLength(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getUTF16Sequence(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getBooleanElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getByteElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getCharElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getShortElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getIntElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getLongElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getFloatElements(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_getDoubleElements(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_returnBooleanElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void rtdroid_002dapp_002ddemo_002eexe_returnByteElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void rtdroid_002dapp_002ddemo_002eexe_returnCharElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void rtdroid_002dapp_002ddemo_002eexe_returnShortElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void rtdroid_002dapp_002ddemo_002eexe_returnIntElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void rtdroid_002dapp_002ddemo_002eexe_returnLongElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void rtdroid_002dapp_002ddemo_002eexe_returnFloatElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void rtdroid_002dapp_002ddemo_002eexe_returnDoubleElements(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
void rtdroid_002dapp_002ddemo_002eexe_getBooleanRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_getByteRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_getCharRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_getShortRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_getIntRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_getLongRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_getFloatRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_getDoubleRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_setBooleanRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_setByteRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_setCharRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_setShortRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_setIntRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_setLongRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_setFloatRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_setDoubleRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_throwInternalError(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_throwNoSuchFieldError(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_throwNoSuchMethodError(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_throwNoSuchMethodError_inJava(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_describeExceptionImpl(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_makeJNIFuncName(uintptr_t arg0,uintptr_t arg1,int32_t arg2,uintptr_t arg3,int8_t arg4);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_processArgs(uintptr_t arg0,int32_t arg1,uintptr_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_getStringRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_getStringUTFRegion(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,uintptr_t arg4);
void rtdroid_002dapp_002ddemo_002eexe_runRunnable(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_javaExit(uintptr_t arg0,int32_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_VMThread_create(uintptr_t arg0,int32_t arg1,int8_t arg2);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_VMThread_createRT(uintptr_t arg0,int32_t arg1,int8_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_VMThread_setThreadState(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_VMThread_getThreadState(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_VMThread_starting(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_VMThread_run(uintptr_t arg0,uintptr_t arg1);
int8_t rtdroid_002dapp_002ddemo_002eexe_VMThread_setUncaughtException(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
void rtdroid_002dapp_002ddemo_002eexe_VMThread_die(uintptr_t arg0,uintptr_t arg1);
int32_t rtdroid_002dapp_002ddemo_002eexe_VMThread_getPriority(uintptr_t arg0,uintptr_t arg1);
int8_t rtdroid_002dapp_002ddemo_002eexe_VMThread_isDaemon(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_String_getArrayPointer(uintptr_t arg0,uintptr_t arg1);
int32_t rtdroid_002dapp_002ddemo_002eexe_String_getOffset(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_allocForNative(uintptr_t arg0,int32_t arg1,uintptr_t arg2);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_allocArrayForNative(uintptr_t arg0,int32_t arg1,uintptr_t arg2,int32_t arg3);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_DirectByteBuffer_wrap(uintptr_t arg0,uintptr_t arg1,int32_t arg2,int32_t arg3,int32_t arg4);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_DirectByteBuffer_address(uintptr_t arg0,uintptr_t arg1);
int32_t rtdroid_002dapp_002ddemo_002eexe_DirectByteBuffer_capacity(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_MemoryArea_getBSID(uintptr_t arg0,uintptr_t arg1);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_BackingStoreID_create(uintptr_t arg0,uintptr_t arg1);
void rtdroid_002dapp_002ddemo_002eexe_MemoryArea_doRun(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2);
uintptr_t rtdroid_002dapp_002ddemo_002eexe_DumpStackCback_cback(uintptr_t arg0,uintptr_t arg1,uintptr_t arg2,int32_t arg3);
static uint32_t usedTids[96] = {
   (uint32_t)INT32_C(2),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(-2),
   (uint32_t)INT32_C(-1),
   (uint32_t)INT32_C(-1),
   (uint32_t)INT32_C(268435455),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(-2),
   (uint32_t)INT32_C(16777215),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(-2),
   (uint32_t)INT32_C(33554431),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(-2),
   (uint32_t)INT32_C(8191),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(-2),
   (uint32_t)INT32_C(262143),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(536870910),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(4094),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(62),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(62),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(14),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(6),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0),
   (uint32_t)INT32_C(0)
};
static int32_t itableOcc[5] = {
   INT32_C(6),
   INT32_C(3),
   INT32_C(4),
   INT32_C(2),
   INT32_C(2)
};
fivmr_Payload rtdroid_002dapp_002ddemo_002eexe_payload = {
   "v0.9.1-rf39719a6391e+",
   "/home/abhijit/development/fivm",
   {
      {
         UINT32_C(1364795540)
,        UINT32_C(272279073)
      }
   },
   &rtdroid_002dapp_002ddemo_002eexe_config,
   FIVMR_PL_IMMORTAL_ONESHOT,
   NULL,
   (int32_t)25,
   (int32_t)120,
   rtdroid_002dapp_002ddemo_002eexe_staticPrimFields,
   rtdroid_002dapp_002ddemo_002eexe_staticRefFields,
   (int32_t)13420,
   (int32_t)393,
   (uintptr_t)0,
   (int32_t)394,
   (int32_t)0,
   (int32_t)2,
   (int32_t)1388,
   (fivmr_TypeData**)rtdroid_002dapp_002ddemo_002eexe_typeList,
   (fivmr_TypeStub*)(&rtdroid_002dapp_002ddemo_002eexe_stubList),
   rtdroid_002dapp_002ddemo_002eexe_contexts,
   (fivmr_DebugRec*)rtdroid_002dapp_002ddemo_002eexe_degugTable,
   (uintptr_t*)rtdroid_002dapp_002ddemo_002eexe_stringTable,
   (uintptr_t*)rtdroid_002dapp_002ddemo_002eexe_stringDataArray,
   NULL,
   (fivmr_Object*)(void*)rtdroid_002dapp_002ddemo_002eexe_stringIndex,
   (uintptr_t*)rtdroid_002dapp_002ddemo_002eexe_classTable,
   (uintptr_t)(intptr_t)-4,
   (uintptr_t)(intptr_t)-4,
   "rtdroid_002dapp_002ddemo_002eexe",
   (&rtdroid_002dapp_002ddemo_002eexe_TypeData_AndroidWrapper_MAsZtvIjmUDHpVxcwSOGQ5),
   usedTids,
   (uintptr_t)12,
   itableOcc,
   (uintptr_t)5,
   NULL,
   0,
   NULL,
   rtdroid_002dapp_002ddemo_002eexe_postThreadInitCback
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_top_bkcp4oGc4D8yEEH7nlTJj6)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_void_au552JrSiVdXJTpoUumvq7)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_boolean_sY8z6fx1V8ILNqgtWTEA35)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_byte_p0EiuVgIFBYQneSwHkWxN2)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_char_GiXZWB9j4vBLRwx6WJyV86)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_short_31w3AaWO7w89oLerGEZ9h3)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_int_gv1gSVUGP0dW3cdLM7LmE8)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_long_ODGjCjLuSmdgk1yysabXl)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_float_jYAb064TTl5ULSaM45eom3)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_double_9qhcjlYcEbW7W8Wvd29o68)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_pointer_sEgXFRMZ4QGvR8UkdPirt7)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_vm_FCPtr_RXJlkedCSLtbjp4C2SYZW2)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_Object_QdKWySJdodzDYbV6VD2VJ)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_String_WHsiOUfdh3VfAocbciMXp7)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_Class_GPw2KraYNcgDw88XQsM0a2)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_Serializable_w2dIMIasUW2jzZi7BO5Wu7)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_Cloneable_e2xIx7PUe02GksGcFKFkr8)
,  NULL
,  NULL
,  NULL
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_WeakReference_aIuqrQ3Ad6912mgziklPD2)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_booleanArr_gfzXZt9jGBwenAc28FEfS6)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_byteArr_nhLAxLkni0PhWM81bwqQW7)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_charArr_l3vFjwWeWLchNa4tr5HoK5)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_shortArr_O9QqSxVPUYeTdeZkUTYxS2)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_intArr_wA4JCC2DA3AFo22aSDOZ76)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_longArr_IyYJgAzIvmrHWyFYSA0Nh5)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_floatArr_5YlNatn3OVHrdzH9hfwKk5)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_doubleArr_mjlqzFmth2EYGUJjMUzYX3)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_pointerArr_mPM8X1CMEIVbdR2ahlrD34)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_vm_FCPtrArr_0jAH6IfIHGlY2R2kAFpWf7)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_ObjectArr_v26WGLx6a25VP6bXhOLzB5)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_StringArr_847AxcZu9gWRJWNEN8DQu5)
,  (fivmr_TypeData*)(&rtdroid_002dapp_002ddemo_002eexe_TypeData_ClassArr_lBldaXgGN9Gu5f4Ma9ms16)
,  rtdroid_002dapp_002ddemo_002eexe_fivmRuntime_boot
,  rtdroid_002dapp_002ddemo_002eexe_fivmRuntime_initSystemClassLoaders
,  rtdroid_002dapp_002ddemo_002eexe_fivmRuntime_notifyInitialized
,  rtdroid_002dapp_002ddemo_002eexe_allocForNative
,  rtdroid_002dapp_002ddemo_002eexe_allocArrayForNative
,  rtdroid_002dapp_002ddemo_002eexe_throwInternalError
,  rtdroid_002dapp_002ddemo_002eexe_throwNoClassDefFoundError_inNative
,  rtdroid_002dapp_002ddemo_002eexe_throwNoClassDefFoundError_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwLinkageError_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwNullPointerRTE
,  rtdroid_002dapp_002ddemo_002eexe_throwNullPointerRTE_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwArithmeticRTE
,  rtdroid_002dapp_002ddemo_002eexe_throwArithmeticRTE_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwStackOverflowRTE
,  rtdroid_002dapp_002ddemo_002eexe_throwStackOverflowRTE_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwClassChangeRTE_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwArrayBoundsRTE_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwArrayStoreRTE_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwNegativeSizeRTE_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwAbstractMethodError_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwClassCastRTE_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwUnsatisfiedLinkErrorForLoad
,  rtdroid_002dapp_002ddemo_002eexe_throwNoSuchFieldError
,  rtdroid_002dapp_002ddemo_002eexe_throwNoSuchMethodError
,  rtdroid_002dapp_002ddemo_002eexe_throwNoSuchMethodError_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwExceptionInInitializerError_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwReflectiveException_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwIllegalMonitorStateException_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwOutOfMemoryError_inJava
,  rtdroid_002dapp_002ddemo_002eexe_throwIllegalAssignmentError
,  rtdroid_002dapp_002ddemo_002eexe_throwIllegalAssignmentError_inJava
,  rtdroid_002dapp_002ddemo_002eexe_describeExceptionImpl
,  rtdroid_002dapp_002ddemo_002eexe_fromCStringInHeap
,  rtdroid_002dapp_002ddemo_002eexe_fromCStringFullInHeap
,  rtdroid_002dapp_002ddemo_002eexe_fromUTF16Sequence
,  rtdroid_002dapp_002ddemo_002eexe_stringLength
,  rtdroid_002dapp_002ddemo_002eexe_cstringLength
,  rtdroid_002dapp_002ddemo_002eexe_getUTF16Sequence
,  rtdroid_002dapp_002ddemo_002eexe_getCString
,  rtdroid_002dapp_002ddemo_002eexe_getCStringFull
,  rtdroid_002dapp_002ddemo_002eexe_getStringRegion
,  rtdroid_002dapp_002ddemo_002eexe_getStringUTFRegion
,  rtdroid_002dapp_002ddemo_002eexe_String_getArrayPointer
,  rtdroid_002dapp_002ddemo_002eexe_String_getOffset
,  rtdroid_002dapp_002ddemo_002eexe_getBooleanElements
,  rtdroid_002dapp_002ddemo_002eexe_getByteElements
,  rtdroid_002dapp_002ddemo_002eexe_getCharElements
,  rtdroid_002dapp_002ddemo_002eexe_getShortElements
,  rtdroid_002dapp_002ddemo_002eexe_getIntElements
,  rtdroid_002dapp_002ddemo_002eexe_getLongElements
,  rtdroid_002dapp_002ddemo_002eexe_getFloatElements
,  rtdroid_002dapp_002ddemo_002eexe_getDoubleElements
,  rtdroid_002dapp_002ddemo_002eexe_returnBooleanElements
,  rtdroid_002dapp_002ddemo_002eexe_returnByteElements
,  rtdroid_002dapp_002ddemo_002eexe_returnCharElements
,  rtdroid_002dapp_002ddemo_002eexe_returnShortElements
,  rtdroid_002dapp_002ddemo_002eexe_returnIntElements
,  rtdroid_002dapp_002ddemo_002eexe_returnLongElements
,  rtdroid_002dapp_002ddemo_002eexe_returnFloatElements
,  rtdroid_002dapp_002ddemo_002eexe_returnDoubleElements
,  rtdroid_002dapp_002ddemo_002eexe_getBooleanRegion
,  rtdroid_002dapp_002ddemo_002eexe_getByteRegion
,  rtdroid_002dapp_002ddemo_002eexe_getCharRegion
,  rtdroid_002dapp_002ddemo_002eexe_getShortRegion
,  rtdroid_002dapp_002ddemo_002eexe_getIntRegion
,  rtdroid_002dapp_002ddemo_002eexe_getLongRegion
,  rtdroid_002dapp_002ddemo_002eexe_getFloatRegion
,  rtdroid_002dapp_002ddemo_002eexe_getDoubleRegion
,  rtdroid_002dapp_002ddemo_002eexe_setBooleanRegion
,  rtdroid_002dapp_002ddemo_002eexe_setByteRegion
,  rtdroid_002dapp_002ddemo_002eexe_setCharRegion
,  rtdroid_002dapp_002ddemo_002eexe_setShortRegion
,  rtdroid_002dapp_002ddemo_002eexe_setIntRegion
,  rtdroid_002dapp_002ddemo_002eexe_setLongRegion
,  rtdroid_002dapp_002ddemo_002eexe_setFloatRegion
,  rtdroid_002dapp_002ddemo_002eexe_setDoubleRegion
,  rtdroid_002dapp_002ddemo_002eexe_returnBuffer
,  rtdroid_002dapp_002ddemo_002eexe_DirectByteBuffer_wrap
,  rtdroid_002dapp_002ddemo_002eexe_DirectByteBuffer_address
,  rtdroid_002dapp_002ddemo_002eexe_DirectByteBuffer_capacity
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_create
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_createRT
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_setThreadState
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_getThreadState
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_starting
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_run
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_setUncaughtException
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_die
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_isDaemon
,  rtdroid_002dapp_002ddemo_002eexe_VMThread_getPriority
,  rtdroid_002dapp_002ddemo_002eexe_DumpStackCback_cback
,  rtdroid_002dapp_002ddemo_002eexe_makeJNIFuncName
,  rtdroid_002dapp_002ddemo_002eexe_runRunnable
,  rtdroid_002dapp_002ddemo_002eexe_MemoryArea_doRun
,  rtdroid_002dapp_002ddemo_002eexe_MemoryArea_getBSID
,  NULL  /* resolution canceled for fivmRuntime_loadClass */
,  NULL  /* resolution canceled for handlePatchPointImpl */
,  NULL  /* resolution canceled for handleLoadThunk */
,  NULL  /* resolution canceled for allocateClass */
,  NULL  /* resolution canceled for handleFieldResolution */
,  NULL  /* resolution canceled for handleMethodResolution */
,  NULL  /* resolution canceled for handleArrayAlloc */
,  NULL  /* resolution canceled for handleObjectAlloc */
,  NULL  /* resolution canceled for handleInstanceof */
,  rtdroid_002dapp_002ddemo_002eexe_BackingStoreID_create
,  rtdroid_002dapp_002ddemo_002eexe_processArgs
,  rtdroid_002dapp_002ddemo_002eexe_javaExit
};
fivmr_StaticTypeContext rtdroid_002dapp_002ddemo_002eexe_contexts[2] = {
   { 0, 356, 0, 0, &rtdroid_002dapp_002ddemo_002eexe_payload },
   { 356, 38, 0, 0, &rtdroid_002dapp_002ddemo_002eexe_payload }
};
