#!/bin/sh
set -e
/home/abhijit/development/fivm/bin/fivmc --more-opt --rt-verbosity-limit 10 --rt-assertions yes --rt-library RTSJ --gc CMR --g-scoped-memory --g-scope-checks no --g-def-immortal-mem 10M --g-def-log true --rtdroid-manifest rtdroid-app-demo.xml -o rtdroid-app-demo.exe ./builds/jar/rtdroid.jar -v 1 --no-regen --no-scripts "$@"
